{% set name = "openfl" %}
{% set version = "1.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openfl-{{ version }}.tar.gz
  sha256: bc2a933a9211e6f1776eb764e81b7599c238fc2eb75fd30b9ed89320b2349f4c

build:
  entry_points:
    - fx=openfl.interface.cli:entry
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }},<3.13
    - grpcio-tools >=1.56.2,<1.66.0
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - click
    - psutil
    - pyyaml
    - rich
    - dynaconf
    - tqdm
    - numpy
    - requests >=2.32.0
    - cloudpickle
    - cryptography
    - pandas
    - scikit-learn
    - flatten_json
    - tensorboardx
    - protobuf >=4.22,<6.0.0
    - grpcio >=1.56.2,<1.66.0

test:
  imports:
    - openfl
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/securefederatedai/openfl
  summary: Secure Federated Learning for the Edge
  license: Apache-2.0
  license_file:
    - LICENSE
    - openfl-docker/licenses.sh

extra:
  recipe-maintainers:
    - sarthakpati
